sudo: required
services:
    - docker

before_install:
    - docker build -t aeonincode/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true aeonincode/frontend npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-290519628345"
    bucket_path: "frontend"
    on:
        branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY